Import('*')

exelibs = [
    env['PRJ_LIBS']['gmock_main'],
    env['PRJ_LIBS']['gmock'],
    env['PRJ_LIBS']['gtest']
]

env.AppendUnique(CCFLAGS='-bigobj')

exename = 'gmock_test'
exe = env.Program(exename, 'gmock_all_test.cc', LIBS=exelibs)
env['PRJ_EXES'][exename] = exe
env['PRJ_TSTS'][exename] = exe


