Import('*')

libname = 'gmock'
lib = env.StaticLibrary(libname, 'gmock-all.cc')
env['PRJ_LIBS'][libname] = lib

libname = 'gmock_main'
lib = env.StaticLibrary(libname, 'gmock_main.cc')
env['PRJ_LIBS'][libname] = lib


